### PR TITLE
Add support for classfull IPv4

### PR DESCRIPTION
**Pull request by Taiki-San**
Address issue https://github.com/whitequark/ipaddr.js/issues/133

### CODE REVIEW

**Comment by whitequark** [comment]
Looks like there's a three octet form too, see [here](https://linux.die.net/man/3/inet_ntoa).

**Comment by Taiki-San** [comment]
Indeed, Internet is a weird place...
I feel like we probably could compact the three (four if we count the three octet form) codepath in one or two, but I'm not sure it's worth the time to avoid code duplication. Any strong feeling one way or another?

**Comment by whitequark** [comment]
Just duplicate it.

**Comment by Taiki-San** [comment]
Ok, just pushed support for 3 octet IPv4

**Pull request merged**
