### PR TITLE
#subnetMatchDual allows range lists to mix IPv4 and IPv6 ranges

### PR DESCRIPTION
**Pull request by bittrance**
As discussed in #56 this adds a separate method for using mixed range lists, but since the implementation differs only one line from original `ipaddr.subnetMatch`, implementation is by a bypass argument on that method that `ipaddr.subnetMatchDual` sets.

Naming such beasts is inevitably hard. I chose "dual" over "hybrid" and "mixed", but I don't have a strong opinion in the matter.

(To keep PR small, built js files are not included.)

### CODE REVIEW

**Comment by whitequark** [comment]
So... on some reflection, it seems *extremely* unlikely that anything will break if we relax the restriction, so let's relax the restriction on `subnetMatch` instead. Also please add a note to the doc.

**Comment by bittrance** [comment]
Have a look now?

**Comment by whitequark** [comment]
Excellent. Unfortunately `ipaddr.min.js` is still broken. When you fix that I will merge.

**Comment by bittrance** [comment]
The broken minified version is likely because `package.json` says `"uglify-js": "latest"` which is now new major version 3 with different API. However, when I do `"uglify-js": "< 3.0"` I get a minified version that is quite different from the one on master. My advise would be that you update `package.json` with the exact version you happen to be using and commit that on master. Then I can rebase on top of that change and build a new version.

**Comment by whitequark** [comment]
Aha, thanks for the pointer.

**Comment by whitequark** [comment]
Done

**Comment by whitequark** [comment]
Merged.

**Pull request closed without merging**
