### PR TITLE
Implement missing methods for IPv6 addresses:

### PR DESCRIPTION
**Pull request by stamfest**
* networkAddressFromCIDR
 * broadcastAddressFromCIDR
 * subnetMaskFromPrefixLength

Note: This is mostly copy/paste from the IPv4 version. So I do not claim any copyright in this. There surely is a more elegant way to implement this for IPv4 and IPv6 in a common manner. But this quick and dirty patch solves the problem for me.

Note: I deliberatly did not include the generated files in this patch, but I can, if you want them in there too...

### CODE REVIEW

**Comment by whitequark** [comment]
IPv6 doesn't have the concept of a broadcast address. IPv6 doesn't have subnet masks. This has been discussed before and I rejected the inclusion of these methods, see #77.

**Comment by stamfest** [comment]
Well, there are subnet masks. And for a system to document IP addresses within networks it is helpful to have the network address functionality to be able help the user to enter them. I take it that you have a very narrow use case in mind for your module. I can live with that and just use the forked version because there currently is nothing better out there.

**Comment by Toxyl** [comment]
> Well, there are subnet masks. And for a system to document IP addresses within networks it is helpful to have the network address functionality to be able help the user to enter them. I take it that you have a very narrow use case in mind for your module. I can live with that and just use the forked version because there currently is nothing better out there.

Exactly, I work in a datacenter and we make a lot of use of that. Thanks to your PR I was able to quickly hack it in, so I don't have to waste time to find a new library.

**Comment by whitequark** [comment]
Let's just reconsider this. The repo the PR is submitted from is stale, but if someone resubmits, I'll merge.

**Comment by Toxyl** [comment]
I've submitted an updated PR of the one made by @stamfest, see https://github.com/whitequark/ipaddr.js/pull/152

**Pull request closed without merging**
