### PR TITLE
Added IPv6 CIDR/subnet support methods

### LINKED ISSUE #68: API symmetry: add `ipaddr.IPv6.subnetMaskFromPrefixLength`
API symmetry: add `ipaddr.IPv6.subnetMaskFromPrefixLength`

### LINKED ISSUE #69: API symmetry: add `ipaddr.IPv6.broadcastAddressFromCIDR`
API symmetry: add `ipaddr.IPv6.broadcastAddressFromCIDR`

### LINKED ISSUE #70: API symmetry: add `ipaddr.IPv6.networkAddressFromCIDR`
API symmetry: add `ipaddr.IPv6.networkAddressFromCIDR`

### LINKED ISSUE #76: Normalizing IPv6 CIDRs, and getting first and last effective host addresses from IPv4 and IPv6
I've come to the realization that I believe #68, #69, #70, and #75 (all related to IPv6 CIDR methods) were all likely closed due to some communication issues over mismatched terminology.

My real usage goal for them was to be able to normalize an IPv6 CIDR to use its first effective host address rather than whatever address was originally provided, much like I can already do for IPv4 CIDRs using their network address, e.g.

```js
ipaddr.processCIDR('ac00::1/24')  // => [ ipaddr.parse('ac00::'), 24 ]

ipaddr.processCIDR('1.2.3.4/5')   // => [ ipaddr.parse('0.0.0.0'), 5 ]
```

As such, I'd like to add some methods to support that cause.  PR forthcoming.

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #76

---

Closes #75
Fixes #68
Fixes #69
Fixes #70

### CODE REVIEW

**Comment by whitequark** [comment]
This is a *huge* chunk of new functionality that seems niche if generally useful at all. I am not convinced that I should merge this, it seems too application-specific. At least I cannot conceive of any use for it.

**Comment by JamesMGreene** [comment]
@whitequark: You don't think it's useful to be able to get the outermost effective host addresses for a subnet from its corresponding CIDR? 😕

**Comment by whitequark** [comment]
Not particularly, especially not in IPv6 since none of network address assignment mechanisms I'm aware of use sequential addresses.

**Comment by JamesMGreene** [comment]
*shrugs* I get the impression you're deeper into the weeds on IPv6 stuff than I am but, from my perspective, these changes are useful and seemingly practical.  If that's not the case for others, though, I can just as easily `require('ipaddr.js')` and extend these onto it within my own codebase.

@silverwind Any thoughts?

**Comment by JamesMGreene** [comment]
FWIW, this seems to be common functionality on almost every web-based CIDR calculator tool that I've encountered, as well as being present in the [`ip6addr` module](https://www.npmjs.com/package/ip6addr)'s API.

**Comment by whitequark** [comment]
Yeah sure it's common but what's it useful for?

**Comment by JamesMGreene** [comment]
For me:
 - Normalizing the CIDR addressing, as done by `processCIDR` (and mentioned in #76)
 - Knowing the minimum and maximum address in the subnet range, which,  in turn, is useful for:
     - checking for inclusion of a single IP
     - checking for overlaps with other CIDRs/subnets/ranges
     - displaying an IP range to users who are not so savvy with CIDR notation

**Comment by whitequark** [comment]
> Normalizing the CIDR addressing, as done by processCIDR (and mentioned in #76)
> checking for inclusion of a single IP
> checking for overlaps with other CIDRs/subnets/ranges

All of these are more easily done using the CIDR form and some basic bitwise operations. A function for checking whether two CIDR ranges overlap would be useful.

> displaying an IP range to users who are not so savvy with CIDR notation

I'm not convinced this is a good enough reason to add this massive chunk of code to ipaddr.js, sorry.

**Comment by silverwind** [comment]
Can this be reconsidered? Getting the first/last addresses in a network is generally useful and I actually already have a use case: Normalizing a user-entered IPv6 CIDR.

**Comment by whitequark** [comment]
Like I said, you only need basic bitwise operations for this. Something like:
```
function normalize(cidrBits) {
  for(var i = 0; i < 8; i++) {
    if(cidrBits > 16) this.parts[i] = 0;
    else this.parts[i] &= ((1 << cidrBits) - 1) << (16 - cidrBits);
  }
}
```

**Comment by silverwind** [comment]
But isn't the point of this library to provide easy-to-use methods? Doing bitwise doesn't really strike me as easy.

One of my projects is currently depending on the branch of this PR and I'd like to get rid of this ugly dependency.

**Comment by whitequark** [comment]
> But isn't the point of this library to provide easy-to-use methods? Doing bitwise doesn't really strike me as easy.

I've already said I'll accept a PR introducing normalization.

> One of my projects is currently depending on the branch of this PR and I'd like to get rid of this ugly dependency.

You can always move the code into your own codebase, no?

**Comment by silverwind** [comment]
> You can always move the code into your own codebase, no?

Already did, thought I see it kind of unnecessary that such a useful feature is not included in this otherwise good library.

**Pull request closed without merging**
