### PR TITLE
Adds TypeScript type guards for address versions

### PR DESCRIPTION
**Pull request by Voronar**
Hi folks!
Here are functions for more ergonomic typed programming.
```typescript
const addr: IPv4 | IPv6 = parse('192.168.1.1');
if (isIPv4(addr)) {
  // addr: IPv4
} else {
  // addr: IPv6
}

if (isIPv6(addr)) {
  // addr: IPv6
} else {
  // addr: IPv4
}
```

### CODE REVIEW

**Comment by whitequark** [comment]
You don't have to message me in every way you can find, I get email for GitHub issues just fine.

**Comment by whitequark** [comment]
Just drop node 8, I think it's EOL

**Comment by Voronar** [comment]
> Just drop node 8, I think it's EOL

Done. Ready for merging.

**Comment by whitequark** [comment]
Please update the Node requirement in README. Then, rebase the branch to contain two commits, Node/CI related changes and the TypeScript changes. After that I'll merge.

**Comment by whitequark** [comment]
I was very sick for a while and this fell off my radar, which unfortunately caused the PR to become unmergeable. Please comment here if you want to update the PR and I'll reopen it.

**Pull request closed without merging**
