### PR TITLE
Simplified the `IPv6.prototype.toString` method

### LINKED ISSUE #84: `IPv6.prototype.toString` result is invalid when first part is `0` but second part is not
`IPv6.prototype.toString` returns an **invalid** result when first part is `0` but second part is not.

Example:

```js
var ipv6String = ipaddr.parse( '0:ff::' ).toString();

/*
Expected:  "::ff:0:0:0:0:0:0"
Actual:    ":ff::"  // invalid IPv6 string
*/
```

I don't have my MBP here today to draft up my own PR fix for this but I'll get to it in the next few days if no one else (e.g. @silverwind or @whitequark) beats me to it.

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #84 

---

While trying to fix #84, I was struggling to figure out quite how your `IPv6#toString` method was working. :confused:

After basically failing to figure it out, I attempted a few different rewrites. This was my favorite rewrite result, which also dramatically simplifies the function to a one-liner with a relatively basic `RegExp`. Hopefully others appreciate this simplification as well! :+1:

### CODE REVIEW

**Comment by silverwind** [comment]
Nice work :)

**Comment by whitequark** [comment]
Thanks! Sometimes a single regexp is worth 40 lines of code.

**Comment by JamesMGreene** [comment]
@whitequark: When you get a chance, please publish a new patch release version for this bug fix.  Thanks!

**Comment by whitequark** [comment]
1.5.4

**Pull request merged**
