### PR TITLE
Updated TypeScript Definitions

### PR DESCRIPTION
**Pull request by claasahl**
Minor updates to TS definitions, which highlight that ...

* IPv4 exposes `octets` (as per README.md)
* Ipv6 exposes `parts` and `zoneId` (as per README.md)
* `prefixLengthFromSubnetMask` actually returns `null` rather than `false`

In addition to the above, I needed to update the dependency `nodeunit`, because it pulled in `tap@14.2.5` which seems to fail in node v5 environments.

### CODE REVIEW

**Comment by whitequark** [comment]
You shouldn't commit `package-lock.json` in a library.

**Comment by claasahl** [comment]
Hi @whitequark 

Thanks for your comment.

From what I understand, the lack of a committed `package-lock.json` was actually the reason why the build for ac8c5fbebab3260befc8c49b347835a91989fc7e failed on travis ci. 

Quoted from https://docs.npmjs.com/files/package-lock.json

>> [...]

>> This file is intended to be committed into source repositories, and serves various purposes:

>> Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

>> [...]

**Comment by whitequark** [comment]
Except libraries shouldn't be tested against the exactly same dependencies, they should be tested against latest dependencies that match the version requirement in their `package.json`.

**Comment by claasahl** [comment]
`package-lock.json` has been removed.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
