### PR TITLE
Update Typescript Definitions and reorganized main script.

### LINKED ISSUE #135: Types had become obsolete
It seems that types had become obsolete for modern TS compiler. Having an issue with this part of code:

```typescript
export const isIpInSubnets = (ip: string, cidrs: Array<string>): boolean => {
    const addr = ipaddr.parse(ip)
    return cidrs.some(cidr => {
        addr.match(ipaddr.parseCIDR(cidr))
        /*   ^^^^^ This expression is not callable.
          Each member of the union type '{ (addr: IPv4, bits: number): boolean; (mask: [IPv4, number]): boolean; } | { (addr: IPv6, bits: number): boolean; (mask: [IPv6, number]): boolean; }' has signatures, but none of those signatures are compatible with each other.ts(2349)*/
    })
}
```

I was able to fix this for myself with a small changes to `ipaddr.js.d.ts`:

```typescript
export class IPv4 extends IP {
    // match(mask: [IPv4, number]): boolean; <--- obsolete definitions
    match(mask: [IPv4 | IPv6, number]): boolean;
}

export class IPv6 extends IP {
    // match(mask: [IPv6, number]): boolean; <--- obsolete definitions
    match(mask: [IPv6 | IPv4, number]): boolean;
}
```

But it feels more like a hack rather than a fix since passing IPv4 subnet to IPv6 class would throw in real life usage.

@raijinsetsu I understand that you wrote this types long time ago but it would be great if you could still come up with a solution here since I'm not that good in TS. With respect.

### PR DESCRIPTION
**Pull request by kennethtran93**
This closes #135.  Using the fix provided in that issue as a base and enhanced it.

Slightly optimized the definitions file

Both files have been reorganized a bit, having the functions sorted by alpha order, within its own IPv4 area, IPv6 area, and common convenience/utility functions.  This makes it slightly easier to read by hand.

Seeing that you're planning on pushing out 2.0.0 it may as well be reorganized.  I do think one should try converting the main js file into typescript, but that's up to you.

Signed-off-by: Kenneth Tran <kennethtran93@users.noreply.github.com>

### CODE REVIEW

**Comment by whitequark** [comment]
> Seeing that you're planning on pushing out 2.0.0 it may as well be reorganized.

I'm actually not sure what you're referring to here?

**Comment by kennethtran93** [comment]
My bad, I mean 'reorganized' as in the organizing the function names alphabetically.  So what I have done is grouped the general utility ones at the bottom of the file, and grouped the rest of the functions into their IPv4 and IPv6 sections.  It still works the same in the user perspective, but if one was to read the source code, I think some organization would help.

This was the same with the TypeScript Definitions.

**Comment by whitequark** [comment]
There's no functional change here at all, right?

**Comment by kennethtran93** [comment]
There shouldn't be any functional changes, with the exception of the TypeScript definitions.  Other Minor changes would be a small clarification/format on some error message but that is it.

**Pull request merged**
