### PR TITLE
Add `IPv4.prototype.toNormalizedString` for symmetry with the IPv6 method

### LINKED ISSUE #67: API symmetry: add `ipaddr.IPv4.prototype.toNormalizedString` method
For API symmetry, it would be nice to add a `ipaddr.IPv4.prototype.toNormalizedString` method to match the IPv6 one.  I'd imagine it just is the same as `toString`, i.e.

```js
ipaddr.IPv4.prototype.toNormalizedString = ipaddr.IPv4.prototype.toString;
```

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #67

### CODE REVIEW

**Comment by JamesMGreene** [comment]
P.S. I'm fine if you don't agree with adding this.

**Comment by whitequark** [comment]
LGTM, can you rebase please?

**Comment by JamesMGreene** [comment]
Rebased.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
