### PR TITLE
Fix zoneIndex parsing for IPv4-mapped IPv6 addresses

### LINKED ISSUE #79: Zone Index is discarded for IPv4-mapped IPv6 (transitional) addresses
Zone Index is discarded for IPv4-mapped IPv6 (transitional) addresses

```js
var ipaddr = require('ipaddr.js')

addr = ipaddr.parse('::ff:ffff:c0a8:101%eth0')
// IPv6 { parts: [ 0, 0, 0, 0, 255, 65535, 49320, 257 ], zoneId: 'eth0' }

addr = ipaddr.parse('::ffff:c0a8:101%z')
// IPv6 { parts: [ 0, 0, 0, 0, 0, 65535, 49320, 257 ], zoneId: 'z' }

// This result is missing its zone index "map"
addr = ipaddr.parse('::ffff:192.168.1.1%map')
// IPv6 { parts: [ 0, 0, 0, 0, 0, 65535, 49320, 257 ] }
```

cc: @silverwind

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #79

### CODE REVIEW

**Comment by JamesMGreene** [comment]
@whitequark @silverwind: So this particular fix also makes me wonder: should you be able to use `IPv6.prototype.toIPv4Address` on an IPv4-mapped address that contains a zone index?

**Comment by silverwind** [comment]
I'd say no for two reasons:

- IPv4 knows no zone index
- AFAIK, zone index can only appear on link-local addresses, which are never ipv4-mapped addresses.

**Comment by JamesMGreene** [comment]
So is this fix irrelevant?

**Comment by JamesMGreene** [comment]
I take it that it does not currently validate if the address is link-local before allowing the zone index to be tacked on.

**Comment by silverwind** [comment]
> So is this fix irrelevant?

Practically yes, but I'd say we still keep those parseable in case anyone ever encounters one. For the zoneId on `IPv6.prototype.toIPv4Address` one could argue similarily. It doesn't really hurt to parse it, I guess. Let's see what @whitequark thinks about `zoneIndex` on the `IPv4` object.

**Comment by JamesMGreene** [comment]
So I'm thinking:
 1. Yes, we still should put this fix in since it is in the core parser logic.
 2. In the IPv6 constructor, we should set the `zoneId` property **IF AND ONLY IF** the address is in the link-local range.
    - If it is not in the link-local range, should we just discard it, or should we throw an Error?

**Comment by silverwind** [comment]
I'd leave it in the IPv6 object in all cases. Today, it's just used for link-local routing, but maybe in the future, it'll be used for more than that. As I said, I think it really doesn't hurt to have it available.

**Comment by whitequark** [comment]
> should you be able to use IPv6.prototype.toIPv4Address on an IPv4-mapped address that contains a zone index?

Sure. Any IPv4-mapped IPv6 address corresponds to an unique IPv4 address, and we have no reason to not return it.

> AFAIK, zone index can only appear on link-local addresses, which are never ipv4-mapped addresses.

That's not true, RFC 4007 defines many uses for scopes and zone indices. Frankly it's a mess but clearly even globally scoped addresses can have a zone index.

<hr>

Resolution: do it syntactically. If a zone index is present on an IPv6 address then parse it and put it into the returned object. Do not look at properties of the address itself.

**Comment by JamesMGreene** [comment]
@whitequark: This PR should be ready to go then.

**Comment by whitequark** [comment]
Thanks!

**Comment by JamesMGreene** [comment]
@whitequark: If you don't end up merging PR #77, I would appreciate a `1.5.1` release with this bug fix. Thanks!

**Comment by whitequark** [comment]
Done

**Pull request merged**
