### PR TITLE
CIDR array response reversed to properly deliminated string

### PR DESCRIPTION
**Pull request by fredthomsen**
Newer to JS and thought I would tackle issue #91 .  I realize this makes another set of tests fail which I can correct, just wanted to see if this approach was acceptable.

### CODE REVIEW

**Comment by whitequark** [comment]
Hm, this looks good to me but it was years since I last touched JS so I'm not sure how much "best practice" is this. @silverwind any comment?

**Comment by silverwind** [comment]
Overriding built-ins is never "good practice" but I don't see another way, so looking fine to me.

**Comment by whitequark** [comment]
> I realize this makes another set of tests fail which I can correct, just wanted to see if this approach was acceptable.

Looks like the CI is green, which tests are failing here?

**Comment by fredthomsen** [comment]
`correctly detects IPv4 and IPv6 CIDR addresses` is failing due to the additional function present in the object when the equality check is done.  Interesting that travis says it's green when you can clearly see the failed assertions in the same output.

**Comment by whitequark** [comment]
OK, hm, that seems like a serious issue because it breaks the public interface. We need another way.

**Comment by fredthomsen** [comment]
True the public interface changes, it's vanilla array vs a array w/the `toString` built-in overridden.  If this change needs to be made, I am not sure I see another way as @silverwind pointed out, besides just punting on this issue.

**Comment by whitequark** [comment]
Maybe a separate method?

**Comment by silverwind** [comment]
Make them non-enumerable properties:

````diff
diff --git a/src/ipaddr.coffee b/src/ipaddr.coffee
index 4c63563..3c31872 100644
--- a/src/ipaddr.coffee
+++ b/src/ipaddr.coffee
@@ -452,9 +452,11 @@ ipaddr.IPv4.parseCIDR = (string) ->
   if match = string.match(/^(.+)\/(\d+)$/)
     maskLength = parseInt(match[2])
     if maskLength >= 0 and maskLength <= 32
       parsed = [@parse(match[1]), maskLength]
-      parsed.toString = () -> this.join('/')
+      Object.defineProperty(parsed, 'toString', {
+        value: () -> this.join('/'),
+      })
       return parsed

   throw new Error "ipaddr: string is not formatted like an IPv4 CIDR range"

@@ -511,9 +513,11 @@ ipaddr.IPv6.parseCIDR = (string) ->
   if match = string.match(/^(.+)\/(\d+)$/)
     maskLength = parseInt(match[2])
     if maskLength >= 0 and maskLength <= 128
       parsed = [@parse(match[1]), maskLength]
-      parsed.toString = () -> this.join('/')
+      Object.defineProperty(parsed, 'toString', {
+        value: () -> this.join('/'),
+      })
       return parsed

   throw new Error "ipaddr: string is not formatted like an IPv6 CIDR range"
````

**Comment by fredthomsen** [comment]
@silverwind 's suggestion causes this to behave as desired.  I've updated the PR with this change.  Thanks.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
