### PR TITLE
bump major version to 2

### PR DESCRIPTION
**Pull request by msimerson**
- kinda late observation: by adding es6 features, support for older versions of node are implicitly dropped
    - since thats likely to be an issue for _someone_, bump the major version
    - bump the min version of nodejs required
- I tried running the build target and discovered that uglify-js doesn't support es6
    - uglify-js has been replaced with uglify-es

### CODE REVIEW

**Comment by whitequark** [comment]
I don't feel like purely internal refactoring should warrant a major version bump.

**Comment by msimerson** [comment]
> I don't feel like purely internal refactoring should warrant a major version bump.

I don't either, but I think dropping support for older versions of nodejs does.

**Comment by whitequark** [comment]
Aren't there some sort of compiler that can take es6 as input and spit out js as output?

**Comment by msimerson** [comment]
Yes, that's exactly what babel is all about. It's a rather heavy weight set of libraries compared to uglify.

**Comment by msimerson** [comment]
AFAIK, the browsers that encompass the first four 9s of usage all all es6 ready, and so are all LTS versions of node, so it'd be a fair bit of work to maintain support for those older 0.001% of potential users. Much easier to just to them, use v1.

**Comment by whitequark** [comment]
I guess.

**Pull request merged**
